(function audioFilmsBootState() {
  function createBootConfig({ issueReports } = {}) {
    const displayPreferenceStorageKeys = {
      displayPreferences: "afShadowingDisplayPreferences",
      learningEnabled: "afShadowingLearningEnabled",
      examplesExpanded: "afDictionaryExamplesExpanded",
      theme: "afShadowingTheme",
    };
    return {
      DICTIONARY_PANEL_ID: "af-shadowing-dictionary-panel",
      RIBBON_PANEL_ID: "af-shadowing-ribbon-panel",
      ROOT_ID: "audiofilms-root",
      SHADOW_CONTAINER_ID: "audiofilms-shadow-container",
      TOGGLE_ID: "af-shadowing-toggle",
      DISPLAY_PREFERENCES_STORAGE_KEY: displayPreferenceStorageKeys.displayPreferences,
      LEARNING_ENABLED_STORAGE_KEY: displayPreferenceStorageKeys.learningEnabled,
      EXAMPLES_EXPANDED_STORAGE_KEY: displayPreferenceStorageKeys.examplesExpanded,
      THEME_STORAGE_KEY: displayPreferenceStorageKeys.theme,
      SOURCE_SELECTION_STORAGE_KEY: "afShadowingSourceSelection",
      MAX_PHRASE_DURATION_MS: 12000,
      LONG_PAUSE_MS: 1000,
      PRE_ROLL_MS: 150,
      POST_ROLL_MS: 500,
      MIN_AUDIBLE_END_TAIL_MS: 300,
      CONTIGUOUS_BOUNDARY_GUARD_MS: 120,
      PLAYBACK_RATE_MIN: 0.25,
      PLAYBACK_RATE_MAX: 2,
      PLAYBACK_RATE_STEP: 0.05,
      DEFAULT_SLOW_REPLAY_SPEED: 0.75,
      ISSUE_REPORT_CATEGORIES: issueReports.issueReportCategories(),
      displayPreferenceStorageKeys,
    };
  }

  function createInitialState({
    bootDiagnostics,
    contentScriptRevision = "",
    initialDisplayPreferences = {},
  } = {}) {
    return {
      videoId: null,
      tracks: [],
      practiceSources: [],
      selectedSourceId: "",
      sourceMenuOpen: false,
      selectedTrack: null,
      cueSource: "",
      transcriptResult: null,
      debugVisible: false,
      debugCopied: false,
      debugPanelInFront: false,
      diagnosticsClearedAt: "",
      cacheRefreshRequested: false,
      issueCopied: false,
      issueDialogOpen: false,
      issueCategory: "navigation",
      issueDescription: "",
      issueExpectedBehavior: "",
      issueIncludeDiagnostics: true,
      issueSubmitting: false,
      issueSubmitStatus: "",
      issueSubmitError: "",
      issueSubmittedId: "",
      debugEvents: [],
      navigationEvents: [],
      lastIssueReport: null,
      backendBuildInfo: null,
      backendBuildError: "",
      navigationEventSeq: 0,
      cues: [],
      phrases: [],
      currentIndex: 0,
      displayPreferences: initialDisplayPreferences,
      learningEnabled: initialDisplayPreferences.enabled,
      textVisible: true,
      shadowTextVisible: true,
      autoPause: initialDisplayPreferences.autoPause,
      practiceMode: "shadow",
      phraseTranslationVisible: false,
      phraseTranslationStickyVisible: false,
      phraseTranslations: {},
      phraseTranslationSeq: 0,
      timingOperation: null,
      timingOperationError: "",
      timingOperationApiBase: "",
      timingOperationPollTimer: null,
      timingOperationAppliedAt: "",
      utilityMenuOpen: false,
      settingsMenuOpen: false,
      shortcutHelpOpen: false,
      phraseJumpMenuOpen: false,
      phraseJumpInput: "",
      phraseJumpError: "",
      lastMenuTrigger: null,
      guidedMode: false,
      selectedWord: null,
      selectedSpan: null,
      spanSelectionDraft: null,
      suppressWordClickUntil: 0,
      dictionaryLookupSeq: 0,
      examplesExpanded: initialDisplayPreferences.examplesExpanded,
      exampleExpansionOverrides: {},
      visibleTranslationsByCardId: {},
      translationPendingByCardId: {},
      audioPendingByCardId: {},
      cardActionFeedbackByCardId: {},
      cardMenuOpenId: "",
      cardMenuFeedbackByCardId: {},
      themePreference: initialDisplayPreferences.theme,
      accountStatus: "guest",
      accountUser: null,
      accountPreferences: null,
      accountError: "",
      accountLoading: false,
      accountMenuOpen: false,
      playbackFrame: null,
      activePlayback: null,
      lastWordReplay: null,
      guidedHold: null,
      passiveVideo: null,
      passiveFrame: null,
      passivePausedKey: "",
      playbackRate: 1,
      pendingPlaybackRateRestore: null,
      lastPhraseProgressRestore: null,
      loading: false,
      loadToken: 0,
      error: "",
      bootDiagnostics,
      contentScriptRevision,
    };
  }

  window.__afShadowingBootState = {
    createBootConfig,
    createInitialState,
  };
})();
