(function audioFilmsSourceLabels() {
  function normalizeText(value) {
    return String(value || "").replace(/\s+/g, " ").trim();
  }

  function stripAutoGeneratedSuffix(value) {
    const label = normalizeText(value);
    return label
      .replace(/\s*\([^)]*(auto-generated|automatisch gegenereerd|automatic|auto)[^)]*\)\s*/i, "")
      .trim() || label;
  }

  function youtubeTextSourceLabel(source, result = null) {
    if (!source) return "";
    if (result?.sourceKind === "asr" || source.track?.afPracticeSnapshotSource) return "ASR transcript";

    const rawName = normalizeText(source.name) || normalizeText(source.track?.name?.simpleText) || normalizeText(source.languageCode) || "Captions";
    const baseName = stripAutoGeneratedSuffix(rawName);
    const isAuto = source.track?.kind === "asr" || result?.sourceKind === "auto";
    return isAuto ? "YouTube transcript (auto-generated)" : "YouTube transcript";
  }

  function timingEnrichmentLabel(result = null) {
    if (!result) return "YouTube timing";
    if (result.sourceKind === "asr") return "ASR timing";
    if (result.timingExactness === "word-level") return "ASR timing";
    if (result.timingExactness === "aligned") return "Aligned timing";
    return "YouTube timing";
  }

  function closedSourceLabel(source, result = null) {
    const sourceLabel = youtubeTextSourceLabel(source, result);
    const enrichment = timingEnrichmentLabel(result);
    return [sourceLabel, enrichment].filter(Boolean).join(" · ") || "Captions";
  }

  function userFacingSourceLabel({ source = null, result = null, hasTracks = false } = {}) {
    if (!source) return hasTracks ? "Captions" : "No captions";
    return closedSourceLabel(source, result);
  }

  function sourceProviderLabel(source, result = null) {
    if (result?.sourceKind === "asr") return "ASR";
    const backendProvider = backendProviderLabel(result);
    if (backendProvider) return backendProvider;
    if (source?.track || result?.fetchOrigin?.startsWith("youtube")) return "YouTube";
    if (result?.provider === "audiofilms-practice-timing") return "YouTube";
    return result?.provider || "";
  }

  function backendProviderLabel(result = null) {
    const isBackend = result?.fetchOrigin === "backend"
      || result?.retrievalPath === "backend-provider"
      || result?.retrievalPath === "practice-timing-cache"
      || result?.retrievalPath === "local-asr-backend";
    if (!isBackend) return "";

    const provider = normalizeText(
      result?.provider === "audiofilms-practice-timing"
        ? result?.practiceSnapshot?.textSource?.provider
        : result?.provider,
    );
    const providerLabel = provider === "yt-dlp"
      ? "yt-dlp"
      : provider === "supadata" ? "Supadata" : "";
    return providerLabel ? `Backend Provider · ${providerLabel}` : "Backend Provider";
  }

  window.__afShadowingSourceLabels = {
    closedSourceLabel,
    userFacingSourceLabel,
    sourceProviderLabel,
    backendProviderLabel,
    stripAutoGeneratedSuffix,
    timingEnrichmentLabel,
    youtubeTextSourceLabel,
  };
})();
