(function audioFilmsSourceLabels() {
  function normalizeText(value) {
    return String(value || "").replace(/\s+/g, " ").trim();
  }

  function stripAutoGeneratedSuffix(value) {
    const label = normalizeText(value);
    return label
      .replace(/\s*\([^)]*(auto-generated|automatisch gegenereerd|automatic|auto)[^)]*\)\s*/i, "")
      .trim() || label;
  }

  function youtubeTextSourceLabel(source, result = null) {
    if (!source) return "";
    if (result?.sourceKind === "asr") return "ASR transcript";

    const rawName = normalizeText(source.name) || normalizeText(source.track?.name?.simpleText) || normalizeText(source.languageCode) || "Captions";
    const baseName = stripAutoGeneratedSuffix(rawName);
    const isAuto = source.track?.kind === "asr" || result?.sourceKind === "auto";
    return isAuto ? `${baseName} (auto-generated)` : baseName;
  }

  function timingEnrichmentLabel(result = null) {
    if (!result || result.sourceKind === "asr") return "";
    if (result.timingExactness === "word-level") return "ASR timing";
    if (result.timingExactness === "aligned") return "Aligned timing";
    return "";
  }

  function closedSourceLabel(source, result = null) {
    const sourceLabel = youtubeTextSourceLabel(source, result);
    const enrichment = timingEnrichmentLabel(result);
    return [sourceLabel, enrichment].filter(Boolean).join(" · ") || "Captions";
  }

  function userFacingSourceLabel({ source = null, result = null, hasTracks = false } = {}) {
    if (!source) return hasTracks ? "Captions" : "No captions";
    return closedSourceLabel(source, result);
  }

  function sourceProviderLabel(source, result = null) {
    if (result?.sourceKind === "asr") return "ASR";
    if (source?.track || result?.fetchOrigin?.startsWith("youtube")) return "YouTube";
    if (result?.provider === "audiofilms-practice-timing") return "YouTube";
    return result?.provider || "";
  }

  window.__afShadowingSourceLabels = {
    closedSourceLabel,
    userFacingSourceLabel,
    sourceProviderLabel,
    stripAutoGeneratedSuffix,
    timingEnrichmentLabel,
    youtubeTextSourceLabel,
  };
})();
