(function audioFilmsSurfaceContentFacade() {
  function createSurfaceControllers(deps = {}) {
    const modules = deps.modules || {};
    const commands = deps.commands || {};
    const constants = deps.constants || {};
    const environment = deps.environment || {};
    const ids = deps.ids || {};

    const ribbonPanelController = modules.ribbonPanelContentWorkflowApi.createRibbonPanelController({
      getState: deps.getState,
      workspaceDom: modules.workspaceDomApi,
      panelId: ids.ribbonPanelId,
      iconSvg: deps.iconSvg,
      bugIconSvg: deps.bugIconSvg,
      ribbonControls: modules.ribbonControlsApi,
      ribbonPanelFactory: modules.ribbonPanelFactoryApi,
      issueReportWorkflow: deps.issueReportWorkflow,
      issueReportCategories: constants.issueReportCategories,
      playbackRateStep: constants.playbackRateStep,
      bringDebugPanelBehindFromPanel: commands.layout.bringDebugPanelBehindFromPanel,
      togglePhraseJumpMenu: commands.navigation.togglePhraseJumpMenu,
      jumpToPhrase: commands.navigation.jumpToPhrase,
      submitPhraseJump: commands.navigation.submitPhraseJump,
      render: commands.render,
      previousPhrase: commands.playback.previousPhrase,
      replayCurrentPhrase: commands.playback.replayCurrentPhrase,
      toggleText: commands.playback.toggleText,
      nextPhrase: commands.playback.nextPhrase,
      setPracticeMode: commands.playback.setPracticeMode,
      togglePhraseTranslation: commands.translation.togglePhraseTranslation,
      toggleSourceMenu: commands.source.toggleSourceMenu,
      cycleThemePreference: commands.display.cycleThemePreference,
      toggleSettingsMenu: commands.display.toggleSettingsMenu,
      toggleShortcutHelp: commands.display.toggleShortcutHelp,
      toggleUtilityMenu: commands.display.toggleUtilityMenu,
      adjustLearnerTextScale: commands.display.adjustLearnerTextScale,
      resetLearnerTextScale: commands.display.resetLearnerTextScale,
      adjustPanelBackgroundAlpha: commands.display.adjustPanelBackgroundAlpha,
      resetPanelBackgroundAlpha: commands.display.resetPanelBackgroundAlpha,
      toggleAutoPause: commands.playback.toggleAutoPause,
      adjustSlowReplaySpeed: commands.playback.adjustSlowReplaySpeed,
      adjustVideoPlaybackRate: commands.playback.adjustVideoPlaybackRate,
      toggleLayoutLock: commands.layout.toggleLayoutLock,
      resetPanelLayout: commands.layout.resetPanelLayout,
      beginPanelDrag: commands.layout.beginPanelDrag,
      beginPanelResize: commands.layout.beginPanelResize,
      toggleDebug: commands.diagnostics.toggleDebug,
      copyDebug: commands.diagnostics.copyDebug,
      clearDiagnostics: commands.diagnostics.clearDiagnostics,
      refreshSelectedSourceCache: commands.source.refreshSelectedSourceCache,
      openIssueReportDialog: commands.issue.openIssueReportDialog,
      submitPhraseBoundaryIssue: commands.issue.submitPhraseBoundaryIssue,
      closeIssueReportDialog: commands.issue.closeIssueReportDialog,
      submitIssueReport: commands.issue.submitIssueReport,
      copyCurrentIssueReport: commands.issue.copyCurrentIssueReport,
      toggleAccountMenu: commands.account.toggleAccountMenu,
      connectAccount: commands.account.connectAccount,
      disconnectAccount: commands.account.disconnectAccount,
    });

    const panelLayoutController = modules.panelLayoutContentWorkflowApi.createPanelLayoutController({
      getState: deps.getState,
      panelLayoutWorkflow: modules.panelLayoutWorkflowApi,
      panelLayout: modules.panelLayoutApi,
      panelLayoutDom: modules.panelLayoutDomApi,
      displayPreferences: modules.displayPreferencesApi,
      HTMLElement: environment.HTMLElement,
      Element: environment.Element,
      document: environment.document,
      window: environment.window,
      rootId: ids.rootId,
      ribbonPanelId: ids.ribbonPanelId,
      dictionaryPanelId: ids.dictionaryPanelId,
      getPanelGestureFallbackInstalled: deps.getPanelGestureFallbackInstalled,
      setPanelGestureFallbackInstalled: deps.setPanelGestureFallbackInstalled,
      getViewportLayoutFrame: deps.getViewportLayoutFrame,
      setViewportLayoutFrame: deps.setViewportLayoutFrame,
      updateDisplayPreferences: commands.display.updateDisplayPreferences,
      render: commands.render,
    });

    const diagnosticsController = modules.diagnosticsContentWorkflowApi.createDiagnosticsController({
      getState: deps.getState,
      diagnosticsWorkflow: modules.diagnosticsWorkflowApi,
      diagnosticsFormatWorkflow: modules.diagnosticsFormatWorkflowApi,
      diagnosticsReport: modules.diagnosticsReportApi,
      issueReports: modules.issueReportsApi,
      captionTracks: modules.captionTrackApi,
      transcriptMetadata: modules.transcriptMetadataApi,
      document: environment.document,
      window: environment.window,
      navigator: environment.navigator,
      getSelectedPracticeSource: commands.source.getSelectedPracticeSource,
      getVideoElement: commands.playback.getVideoElement,
      describePhraseAtIndex: commands.playback.describePhraseAtIndex,
      extensionBuildInfo: deps.extensionBuildInfo,
      publishDiagnosticsSnapshot: commands.diagnostics.publishDiagnosticsSnapshot,
      copyTextWithFallback: commands.diagnostics.copyTextWithFallback,
      roundTime: commands.playback.roundTime,
      render: commands.render,
    });

    const keyboardController = modules.keyboardContentWorkflowApi.createKeyboardController({
      getState: deps.getState,
      keyboardWorkflow: modules.keyboardWorkflowApi,
      isWatchPage: modules.youtubeAdapterApi.isWatchPage,
      keyboardShortcuts: modules.keyboardShortcutApi,
      toggleContinuousPlayback: commands.playback.toggleContinuousPlayback,
      clearSpanSelectionDraft: commands.dictionary.clearSpanSelectionDraft,
      closeOpenMenus: commands.display.closeOpenMenus,
      toggleShortcutHelp: commands.display.toggleShortcutHelp,
      nextPhrase: commands.playback.nextPhrase,
      previousPhrase: commands.playback.previousPhrase,
      replayCurrentPhrase: commands.playback.replayCurrentPhrase,
      toggleText: commands.playback.toggleText,
      adjustVideoPlaybackRate: commands.playback.adjustVideoPlaybackRate,
      togglePhraseTranslation: commands.translation.togglePhraseTranslation,
      setPracticeMode: commands.playback.setPracticeMode,
      playbackRateStep: constants.playbackRateStep,
    });

    const displayStateController = modules.displayStateContentWorkflowApi.createDisplayStateController({
      getState: deps.getState,
      displayPreferenceWorkflow: modules.displayPreferenceWorkflowApi,
      uiStateWorkflow: modules.uiStateWorkflowApi,
      displayPreferences: modules.displayPreferencesApi,
      menuState: modules.menuStateApi,
      playbackSession: modules.playbackSessionApi,
      playbackRateOptions: deps.playbackRateOptions,
      getVideoElement: commands.playback.getVideoElement,
      updateDisplayPreferences: commands.display.updateDisplayPreferences,
      recordDebugEvent: commands.diagnostics.recordDebugEvent,
      document: environment.document,
      Element: environment.Element,
      rootId: ids.rootId,
      requestAnimationFrame: environment.requestAnimationFrame,
      render: commands.render,
    });

    const ribbonContentController = modules.ribbonContentWorkflowApi.createRibbonContentController({
      getState: deps.getState,
      sourceSelectorWorkflow: modules.sourceSelectorWorkflowApi,
      sourceSelector: modules.sourceSelectorApi,
      sourceSelectorDom: modules.sourceSelectorDomApi,
      sourceReadiness: modules.sourceReadinessApi,
      sourceLabels: modules.sourceLabelsApi,
      captionTracks: modules.captionTrackApi,
      phraseRowsWorkflow: modules.phraseRowsWorkflowApi,
      phraseRows: modules.phraseRowsApi,
      phraseRowsDom: modules.phraseRowsDomApi,
      selectedSpanWorkflow: modules.selectedSpanWorkflowApi,
      selectedSpans: modules.selectedSpanApi,
      getSelectedPracticeSource: commands.source.getSelectedPracticeSource,
      practiceReadiness: commands.source.practiceReadiness,
      timingOperationState: commands.source.timingOperationState,
      userFacingSourceLabel: commands.source.userFacingSourceLabel,
      refreshSelectedSourceCache: commands.source.refreshSelectedSourceCache,
      startImproveTiming: commands.source.startImproveTiming,
      selectPracticeSource: commands.source.selectPracticeSource,
      phraseTranslationState: commands.translation.phraseTranslationState,
      playbackEndMsForPhrase: commands.playback.playbackEndMsForPhrase,
      applySpanSelectionDraftPreview: commands.dictionary.applySpanSelectionDraftPreview,
      clearSpanSelectionDraft: commands.dictionary.clearSpanSelectionDraft,
      selectLookupWord: commands.dictionary.selectLookupWord,
      handleWordReplayGesture: commands.dictionary.handleWordReplayGesture,
      requestSelectedSpanTranslation: commands.translation.requestSelectedSpanTranslation,
      clearElement: modules.domUtilsApi.clearElement,
      render: commands.render,
    });

    return {
      ribbonPanelController,
      panelLayoutController,
      diagnosticsController,
      keyboardController,
      displayStateController,
      ribbonContentController,
    };
  }

  window.__afShadowingSurfaceContentFacade = {
    createSurfaceControllers,
  };
})();
